config/routes.rb
Rails.application.routes.draw do
  resources :vita
  resources :yolos do
    resources :comments, module: :yolos
    member do
      put "like", to: "yolos#upvote"
      put "dislike", to: "yolos#downvote"
    end
  end

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  mount Soulmate::Server, :at => "/autocomplete"

  devise_for :users, controllers: {registrations: 'user_registrations'}

  get 'conversations/show'

  get 'conversations/create'

  resources :application_forms
  resources :media
  resources :groups do
    resources :posts, module: :groups
    member do
      get :join
      get :unfollow
    end
  end

  post '/buy/:slug', to: 'transactions#create', as: :buy

  resources :online_learnings
  resources :categories
  resources :videos
  resources :lectures
  resources :syllabuses
  resources :courses
  resources :polls
  resources :poll_votes, only: [:create]
  resources :community_posts

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :events do
    resources :posts, module: :events
  end

  get 'notifications/' => "notifications#index"

  resources :classifieds do
    resources :transactions, only: [:purchase, :create, :pickup], module: :classifieds
  end

  post "/hook" => "classifieds#hook"
  
  get "/classifieds/:id/purchase", to: "classifieds#purchase", as: :purchase_classified

  resources :posts, only: [:create, :edit, :update, :destroy] do
    resources :comments, module: :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :activities, only: [:index] do
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end

  resources :job_applications do
    resources :transactions, only: [:purchase, :create, :pickup], module: :job_applications
  end
  
  root 'pages#home'

  post "/activity_create" => "posts#create_from_activity"

  get "/about" => "pages#about"
  get "/community" => "pages#community"
  get "/contact" => "pages#contact"
  get "/copyright" => "pages#copyright"
  get "/privacy" => "pages#privacy"
  get "/terms" => "pages#terms"
  get "/toc" => "pages#toc"
  get "/cookies" => "pages#cpolicy"

  get "/find_university" => "pages#find_university"
  get "/find_tutor" => "pages#find_tutor"

  get '/users/:id/job_applications', to: 'job_applications#job_applications', as: 'user_job_applications'

  
  resources :users, only: [:show, :index]

  resources :detailbooks do
    resources :educations
    resources :job_experiences
  end
  resources :users do
    resources :posts, module: :users
    resources :educations
    resources :job_experiences
    resources :benchmark_reports, only: [:index, :show, :create, :new]
    resources :ex_files
    resources :skills
    resources :todo_tasks 
    resources :vita, only: [:index]
    resources :interest_activities
  end
  resources :skills
  resources :todo_tasks

  
  resources :friendships, only: [:create, :destroy, :accept] do 
    resources :comments, module: :friendships
    member do 
      put :accept
      put "like", to: "friendships#upvote"
      put "dislike", to: "friendships#downvote"
    end
  end

  resources :follows, only: [:follow, :unfollow] do
    member do
      get "follow"
      get "unfollow"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/benchmark_report.rb
class BenchmarkReport < ActiveRecord::Base
  belongs_to :user

  # scheduler = Rufus::Scheduler.new

 #  scheduler.cron '59 59 23 L * *' do
	# # every month on the last day at 23:59:59
	# students = User.all.where(role: "s") # Gets all students
	# max = students.order("benchmark desc").first.benchmark # Gets the highest benchmark
	# avg = students.order("benchmark desc").average(:benchmark).to_i # Gets the average benchmark from all students

	# students.each do |student| # For every student ...
	# 	BenchmarkReport.create(student, student.benchmark, Time.now().month, Time.now().year, avg, max) # ... create a benchmark report!
	# end
 #  end

	# scheduler.every '3m' do
		
 # 	end

end

app/controllers/benchmark_reports_controller.rb
class BenchmarkReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_benchmark_report, only: [:show, :edit, :update, :destroy]

  # GET /benchmark_reports
  # GET /benchmark_reports.json
  def index
    @benchmark_reports = @user.benchmark_reports.all
    # gon.rabl "app/views/benchmark_reports/index.json.rabl", as: "benchmark"

    points = []
    period = []
    avg = []
    max = []

    @benchmark_reports.each do |benchmark|
      points.push(benchmark.points)
      period.push(benchmark.month.to_s + '/' + benchmark.year.to_s)
      avg.push(benchmark.average)
      max.push(benchmark.maximum)
    end
    
    @data = { labels: period, 
              datasets: [
                {
                  label: "Highest Benchmark",
                  fillColor: "rgba(189, 80, 43, 0.0)",
                  strokeColor: "rgba(189, 80, 43, 1)",
                  pointColor: "rgba(189, 80, 43, 1)",
                  pointStrokeColor: "#fff",
                  pointHighlightFill: "#fff",
                  pointHighlightStroke: "rgba(189, 80, 43, 1)",
                  data: max
                },
                {
                  label: "Your Benchmark",
                  fillColor: "rgba(80, 179, 110, 0.0)",
                  strokeColor: "rgba(80, 179, 110, 1)",
                  pointColor: "rgba(80, 179, 110, 1)",
                  pointStrokeColor: "#fff",
                  pointHighlightFill: "#fff",
                  pointHighlightStroke: "rgba(80, 179, 110, 1)",
                  data: points
                },
                {
                  label: "Average Benchmark",
                  fillColor: "rgba(60, 155, 207, 0.0)",
                  strokeColor: "rgba(60, 155, 207, 1)",
                  pointColor: "rgba(60, 155, 207, 1)",
                  pointStrokeColor: "#fff",
                  pointHighlightFill: "#fff",
                  pointHighlightStroke: "rgba(60, 155, 207, 1)",
                  data: avg
                }
              ]
            }

      @options = {
        generateLegend: true,
        width: 560,

        # Boolean - Whether grid lines are shown across the chart
        scaleShowGridLines: true,

        # String - Colour of the grid lines
        scaleGridLineColor: "rgba(0,0,0,.05)",

        # Number - Width of the grid lines
        scaleGridLineWidth: 1,

        # Boolean - Whether to show horizontal lines (except X axis)
        scaleShowHorizontalLines: true,

        # Boolean - Whether to show vertical lines (except Y axis)
        scaleShowVerticalLines: true,

        # Boolean - Whether the line is curved between points
        bezierCurve: true,

        # Number - Tension of the bezier curve between points
        bezierCurveTension: 0.4,

        # Boolean - Whether to show a dot for each point
        pointDot: true,

        # Number - Radius of each point dot in pixels
        pointDotRadius: 4,

        # Number - Pixel width of point dot stroke
        pointDotStrokeWidth: 1,

        # Number - amount extra to add to the radius to cater for hit detection outside the drawn point
        pointHitDetectionRadius: 20,

        # Boolean - Whether to show a stroke for datasets
        datasetStroke: true,

        # Number - Pixel width of dataset stroke
        datasetStrokeWidth: 2,

        # Boolean - Whether to fill the dataset with a colour
        datasetFill: true,

        # String - A legend template
        legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\">&nbsp;&nbsp;&nbsp;&nbsp;</span><%if(datasets[i].label){%>&nbsp;<%=datasets[i].label%><%}%></li><%}%></ul>",
        
        tooltipTemplate: "<%if (label){%><%=label%>: <%}%><%= value %>"
      }
  end

  # GET /benchmark_reports/1
  # GET /benchmark_reports/1.json
  def show
  end

  # GET /benchmark_reports/new
  def new
    @benchmark_report = @user.benchmark_reports.new
  end

  # GET /benchmark_reports/1/edit
  def edit
  end

  # POST /benchmark_reports
  # POST /benchmark_reports.json
  def create
    @benchmark_report = @user.benchmark_reports.new(benchmark_report_params)

    respond_to do |format|
      if @benchmark_report.save
        format.html { redirect_to @benchmark_report, notice: 'Benchmark report was successfully created.' }
        format.json { render :show, status: :created, location: @benchmark_report }
      else
        format.html { render :new }
        format.json { render json: @benchmark_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /benchmark_reports/1
  # PATCH/PUT /benchmark_reports/1.json
  def update
    respond_to do |format|
      if @benchmark_report.update(benchmark_report_params)
        format.html { redirect_to @benchmark_report, notice: 'Benchmark report was successfully updated.' }
        format.json { render :show, status: :ok, location: @benchmark_report }
      else
        format.html { render :edit }
        format.json { render json: @benchmark_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /benchmark_reports/1
  # DELETE /benchmark_reports/1.json
  def destroy
    @benchmark_report.destroy
    respond_to do |format|
      format.html { redirect_to benchmark_reports_url, notice: 'Benchmark report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_benchmark_report
      @benchmark_report = BenchmarkReport.find(params[:id])
    end

    # Use to call the user
    def set_user
      @user = User.find_by(username: params[:user_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def benchmark_report_params
      params.require(:benchmark_report).permit(:user_id, :points, :month, :year, :average, :maximum)
    end
end

# class cona
#   before_action :authenticate_user!, only: [:index, :job_applications]
#   before_action :set_user, only: [:show, :job_applications]
#   before_action :get_counts, only: [:index]

#   def index
#     case params[:people]
#     when "friends"
#       @users = current_user.active_friends
#     when "requests"
#       @users = current_user.pending_friend_requests_from.map(&:user)
#     when "pending"
#       @users = current_user.pending_friend_requests_to.map(&:friend)
#     when "students"
#       @users = User.where(role: "s").where.not(id: current_user.id)
#     when "tutors"
#       @users = User.where(role: "t").where.not(id: current_user.id)
#     when "universities"
#       @users = User.where(role: "u").where.not(id: current_user.id)
#     when "businesses"
#       @users = User.where(role: "b").where.not(id: current_user.id)
#     else
#       @users = User.where.not(id: current_user.id)
#     end
#   end

#   def show
#     @post = Post.new
#     @posts = @user.posts.order('created_at DESC')
#     @activities = PublicActivity::Activity.where(owner_id: @user.id).order('created_at DESC')
#     @quote = get_quote
#   end

#   private

#   def get_counts
#     @friend_count = current_user.active_friends.size
#     @pending_count = current_user.pending_friend_requests_to.map(&:friend).size
#   end

#   def set_user
#     @user = User.find_by(username: params[:id])
#   end

#   def get_quote
#     quotes = [
#         "Education is not preparation for life; education <i>is</i> life itself.<br> – John Dewey",
#         "We have all much to learn: Let us teach one another as <i>kindly</i> as we can.<br> – Reade",
#         "Few of us know what we are capable of doing . . .; <i>We have never pushed ourselves</i> hard enough to find out.<br> – Alfred A. Montapert",
#         "Success seems to be largely a matter of <i>hanging on</i> after others have let go.<br> – William Feather",
#         "If you want learning, you must <i>work</i> for it.<br> – Josiah Gilbert Holland",
#         "Achievements are the accomplishment of <i>persistent</i> individuals.<br> – James Jones",
#         "Failing to prepare is preparing to fail.<br> – Anonymous"
#       ] 
#     index = Random.rand(quotes.size - 1)

#     return quotes[index]
#   end
# end

app/helpers/benchmark_reports_helper.rb
module BenchmarkReportsHelper
end

app/views/benchmark_reports/_form.html.haml
= simple_form_for(@benchmark_report) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :points
    = f.input :month
    = f.input :year

  .form-actions
    = f.button :submit

app/views/benchmark_reports/_header.html.haml
.row.panel{style: "border: 1px solid #CECECE;"}
  .col-md-4.bg_blur{ style: "background-image:url(#{ image_path @user.background.url });" }
  .col-md-8.col-xs-12
    = image_tag @user.avatar.url(:medium), class: "img-thumbnail picture hidden-xs"
    = image_tag @user.avatar.url(:medium), class: "img-thumbnail visible-xs picture_mob"
    .header
      - if @user.full_name != nil
        %h1= @user.full_name
      - else
        %h1= @user.username
      %h4
        = @user.roles.first.name.camelize
        - if @user.student?
          %span.label.label-default.rank-label= 'BM: '+@user.benchmark.to_s
      %blockquote
        %p Dream big dreams. Small dreams have no magic.
      .pull-right{style: "margin-right: 70px;"}
        - if current_user != @user
          = action_buttons(@user)
    .row.nav{style: "padding-bottom: 0px;"}
      .col-md-8.col-md-offset-2.col-xs-12.navButtons{style: "padding: 0px; padding-top: 37px;"}
        - if @user.student?
          = link_to user_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-comments-o
          = link_to medium_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-camera-retro
          = link_to user_vita_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-video-camera
          = link_to user_benchmark_reports_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-area-chart
        - if @user.business?
          = link_to application_forms_path do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-bookmark
          = link_to medium_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-newspaper-o
          = link_to user_job_applications_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-files-o
          = link_to user_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-comments-o


/ .profile-header.text-center{:style => "background-image: url(#{ image_path @user.background.url }); "}
/   .container-fluid
/     .container-inner
/       .profile-header-container
/         .profile-header-img
/           = image_tag @user.avatar.url, class: "img-circle media-object"
/         - if @user.student?
/           .rank-label-container
/             %span.label.label-default.rank-label= 'BM: '+@user.benchmark.to_s
/       %h3.profile-header-user
/         - if @user.full_name != nil
/           = @user.full_name
/         - else
/           = @user.username
/       %p.profile-header-bio= @user.roles.first.name.camelize
/   %nav.profile-header-nav
/     / %ul.nav.nav-tabs
/     /   %li= link_to " Interaction", user_path(@user.username), class: "fa fa-comments-o"
/     /   %li.active= link_to " Gallery", medium_path(@user.username), class: "fa fa-camera-retro"
/     /   %li= link_to " Exchange Notes", folders_path(@user.username), class: "fa fa-files-o"
/     /   - if current_user.student?
/     /     %li= link_to " My Detailbook", detailbooks_path, class: "fa fa-globe"
/     %ul.nav.nav-tabs
/       - if @user.student?
/         %li
/           = link_to user_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-comments-o{ style: "color: #50b36e; font-weight: bold;"}
/             Streamline
/         %li
/           = link_to medium_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-camera-retro{ style: "font-weight: bold; color: #3c9bcf;" }
/             Gallery
/         - if !current_user.business?
/           %li
/             = link_to user_ex_files_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/               %i.fa.fa-files-o{ style: "font-weight: bold; color: #000;" }
/               Exchange Notes
/       - elsif @user.business?
/         / -if @user.university?
/         /   %li
/         /     = link_to medium_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/         /       %i.fa.fa-camera-retro{ style: "color: #3097d1; font-weight: bold;" }
/         /       University Updates
/         /   %li
/         /     = link_to user_ex_files_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/         /       %i.fa.fa-folder-o{ style: "color: #3097d1; font-weight: bold;" }
/         /       University Folder
/         / - elsif @user.business?
/         %li
/           = link_to application_forms_path, style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-bookmark{ style: "color: #3c9bcf; font-weight: bold;" }
/             CV Library
/         %li
/           = link_to medium_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-newspaper-o{ style: "color: #d9c918; font-weight: bold;" }
/             Gallery
/         / %li
/         /   = link_to folders_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/         /     %i.fa.fa-files-o{ style: "color: #3097d1; font-weight: bold;" }
/         /     Company Reports
/         %li
/           = link_to user_job_applications_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-files-o{ style: "color: #bd502b; font-weight: bold;" }
/             Jobs Archive
/         %li
/           = link_to user_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-comments-o{ style: "color: #50b36e; font-weight: bold;"}
/             My Seeds
/       - if @user.student?
/         %li.active
/           = link_to user_benchmark_reports_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;", "data-no-turbolink" => true do
/             %i.fa.fa-area-chart{ style: "font-weight: bold; color: #bd502b;"}
/             Benchmark
/

app/views/benchmark_reports/create.html.haml
%h1 BenchmarkReports#create
%p Find me in app/views/benchmark_reports/create.html.haml

app/views/benchmark_reports/edit.html.haml
%h1 Editing benchmark_report

= render 'form'

= link_to 'Show', @benchmark_report
\|
= link_to 'Back', benchmark_reports_path

app/views/benchmark_reports/index.html.haml
-# .better{ style: "background-color: #30526E;" }
%div{ style: "padding-top: 35px;" }
= render 'header'
.container-fluid
	.row
		%h1.text-center #{ @user.first_name }'s Benchmark
		/ %p Find me in app/views/benchmark_reports/index.html.haml

		.col-md-6
			.panel.panel-default.text-center
				- if @benchmark_reports != nil && @benchmark_reports != []
					= line_chart @data, @options

				- else
					There is no benchmark reports available. Wait until the end of the month, to showcase your first benchmark report.

		.col-md-5.col-md-offset-1
			.panel.panel-default.text-center
				%h3 How the benchmark works?
				%p Benchmarks are used to analyse the users' progress, on a competitive level against other users.
				%p

app/views/benchmark_reports/new.html.haml
%h1 New benchmark_report

= render 'form'

= link_to 'Back', benchmark_reports_path

app/views/benchmark_reports/show.html.haml
%p#notice= notice

%p
  %b User:
  = @benchmark_report.user
%p
  %b Points:
  = @benchmark_report.points
%p
  %b Month:
  = @benchmark_report.month
%p
  %b Year:
  = @benchmark_report.year

= link_to 'Edit', edit_benchmark_report_path(@benchmark_report)
\|
= link_to 'Back', benchmark_reports_path