config/routes.rb
Rails.application.routes.draw do
  resources :vita
  resources :yolos do
    resources :comments, module: :yolos
    member do
      put "like", to: "yolos#upvote"
      put "dislike", to: "yolos#downvote"
    end
  end

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  mount Soulmate::Server, :at => "/autocomplete"

  devise_for :users, controllers: {registrations: 'user_registrations'}

  get 'conversations/show'

  get 'conversations/create'

  resources :application_forms
  resources :media
  resources :groups do
    resources :posts, module: :groups
    member do
      get :join
      get :unfollow
    end
  end

  post '/buy/:slug', to: 'transactions#create', as: :buy

  resources :online_learnings
  resources :categories
  resources :videos
  resources :lectures
  resources :syllabuses
  resources :courses
  resources :polls
  resources :poll_votes, only: [:create]
  resources :community_posts

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :events do
    resources :posts, module: :events
  end

  get 'notifications/' => "notifications#index"

  resources :classifieds do
    resources :transactions, only: [:purchase, :create, :pickup], module: :classifieds
  end

  post "/hook" => "classifieds#hook"
  
  get "/classifieds/:id/purchase", to: "classifieds#purchase", as: :purchase_classified

  resources :posts, only: [:create, :edit, :update, :destroy] do
    resources :comments, module: :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :activities, only: [:index] do
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end

  resources :job_applications do
    resources :transactions, only: [:purchase, :create, :pickup], module: :job_applications
  end
  
  root 'pages#home'

  post "/activity_create" => "posts#create_from_activity"

  get "/about" => "pages#about"
  get "/community" => "pages#community"
  get "/contact" => "pages#contact"
  get "/copyright" => "pages#copyright"
  get "/privacy" => "pages#privacy"
  get "/terms" => "pages#terms"
  get "/toc" => "pages#toc"
  get "/cookies" => "pages#cpolicy"

  get "/find_university" => "pages#find_university"
  get "/find_tutor" => "pages#find_tutor"

  get '/users/:id/job_applications', to: 'job_applications#job_applications', as: 'user_job_applications'

  
  resources :users, only: [:show, :index]

  resources :detailbooks do
    resources :educations
    resources :job_experiences
  end
  resources :users do
    resources :posts, module: :users
    resources :educations
    resources :job_experiences
    resources :benchmark_reports, only: [:index, :show, :create, :new]
    resources :ex_files
    resources :skills
    resources :todo_tasks 
    resources :vita, only: [:index]
    resources :interest_activities
  end
  resources :skills
  resources :todo_tasks

  
  resources :friendships, only: [:create, :destroy, :accept] do 
    resources :comments, module: :friendships
    member do 
      put :accept
      put "like", to: "friendships#upvote"
      put "dislike", to: "friendships#downvote"
    end
  end

  resources :follows, only: [:follow, :unfollow] do
    member do
      get "follow"
      get "unfollow"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/ex_file.rb
class ExFile < ActiveRecord::Base
	belongs_to :user
	belongs_to :category

	has_attached_file :attachment
	# validates_attachment_presence :attachment
	validates_attachment_content_type :attachment,
		:content_type => ['video/mp4', 'video/flv', 'video/webm'],
		:message => "Sorry, right now we only support MP4, FLV and WEBm videos",
		:if => :is_type_of_video?
	validates_attachment_content_type :attachment,
		:content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
		:message => "Image error message",
		:if => :is_type_of_image?
	validates_attachment_content_type :attachment,
		:content_type => ['application/txt', 'application/pdf', 'application/msword',
			'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			'application/vnd.oasis.opendocument.text', 'application/x-vnd.oasis.opendocument.text',
			'application/rtf', 'application/x-rtf', 'application/doc', 
			'application/docx', 'application/x-soffice', 'application/octet-stream'],
		:message => "Document error message",
		:if => :is_type_of_document?
	validates_attachment_content_type :attachment,
		:content_type => ['text/richtext', 'text/rtf', 'text/plain'],
		:message => "Document error message",
		:if => :is_type_of_text?

	protected

	def is_type_of_video?
		attachment.content_type =~ %r(video)
	end

	def is_type_of_image?
		attachment.content_type =~ %r(image)
	end

	def is_type_of_document?
		attachment.content_type =~ %r(application)
	end

	def is_type_of_text?
		attachment.content_type =~ %r(text)
	end

end

app/controllers/ex_files_controller.rb
class ExFilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_ex_file, only: [:show, :edit, :update, :destroy]

  # GET /ex_files
  # GET /ex_files.json
  def index
    if params[:cat]
      @ex_files = current_user.ex_files.all.where(category_id: Category.where(slug: params[:cat]))
    else
      @ex_files = current_user.ex_files.all
    end
  end

  # GET /ex_files/1
  # GET /ex_files/1.json
  def show
    redirect_to @ex_file.attachment.url
  end

  # GET /ex_files/new
  def new
    @ex_file = current_user.ex_files.new
  end

  # GET /ex_files/1/edit
  def edit
  end

  # POST /ex_files
  # POST /ex_files.json
  def create
    @ex_file = current_user.ex_files.new(ex_file_params)
    @ex_file.guid = SecureRandom.base64[1..11]

    respond_to do |format|
      if @ex_file.save
        format.html { redirect_to user_ex_files_url(current_user.username), notice: 'File was successfully created.' }
        format.json { render :show, status: :created, location: @ex_file }
      else
        format.html { render :new }
        format.json { render json: @ex_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ex_files/1
  # PATCH/PUT /ex_files/1.json
  def update
    @user = User.find(params[:user_id])
    @ex_file = @user.ex_files.find(params[:id])

    respond_to do |format|
      if @ex_file.update(ex_file_params)
        format.html { redirect_to user_ex_file_url(@user.username, @ex_file.guid), notice: 'File was successfully updated.' }
        format.json { render :show, status: :ok, location: @ex_file }
      else
        format.html { render :edit }
        format.json { render json: @ex_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ex_files/1
  # DELETE /ex_files/1.json
  def destroy
    @ex_file.destroy
    respond_to do |format|
      format.html { redirect_to user_ex_files_url(@user.username), notice: 'File was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ex_file
      @ex_file = ExFile.find_by_guid(params[:id])
    end

    def set_user
      @user = User.find_by(username: params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ex_file_params
      params.require(:ex_file).permit(:user_id, :name, :description, :category_id, :guid, :attachment)
    end
end

app/helpers/ex_files_helper.rb
module ExFilesHelper
end

app/views/ex_files/_form.html.haml
= simple_form_for([@user, @ex_file]) do |f|
	= f.error_notification

	.form-inputs
		= f.file_field :attachment
		/ = f.association :user
		= f.input :name
		= f.input :description
		= f.association :category
		/ = f.input :guid

	.form-actions
		= f.button :submit

app/views/ex_files/_header.html.haml
.row.panel{style: "border: 1px solid #CECECE;"}
  .col-md-4.bg_blur{ style: "background-image:url(#{ image_path @user.background.url });" }
  .col-md-8.col-xs-12
    = image_tag @user.avatar.url(:medium), class: "img-thumbnail picture hidden-xs"
    = image_tag @user.avatar.url(:medium), class: "img-thumbnail visible-xs picture_mob"
    .header
      - if @user.full_name != nil
        %h1= @user.full_name
      - else
        %h1= @user.username
      %h4
        = @user.roles.first.name.camelize
        - if @user.student?
          %span.label.label-default.rank-label= 'BM: '+@user.benchmark.to_s
      %blockquote
        %p Dream big dreams. Small dreams have no magic.
      .pull-right{style: "margin-right: 70px;"}
        - if current_user != @user
          = action_buttons(@user)
    .row.nav{style: "padding-bottom: 0px;"}
      .col-md-8.col-md-offset-2.col-xs-12.navButtons{style: "padding: 0px; padding-top: 37px;"}
        - if @user.student?
          = link_to user_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-comments-o
          = link_to medium_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-camera-retro
          = link_to user_vita_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-video-camera
          = link_to user_benchmark_reports_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-area-chart
        - if @user.business?
          = link_to application_forms_path do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-bookmark
          = link_to medium_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-newspaper-o
          = link_to user_job_applications_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-files-o
          = link_to user_path(@user.username) do
            .col-md-3.col-xs-3.well{ style: "border: 0px;" }
              %i.fa.fa-comments-o


/ .profile-header.text-center{:style => "background-image: url(#{ image_path @user.background.url }); "}
/   .container-fluid
/     .container-inner
/       .profile-header-container
/         .profile-header-img
/           = image_tag @user.avatar.url, class: "img-circle media-object"
/         - if @user.student?
/           .rank-label-container
/             %span.label.label-default.rank-label= 'BM: '+@user.benchmark.to_s
/       %h3.profile-header-user
/         - if @user.full_name != nil
/           = @user.full_name
/         - else
/           = @user.username
/       %p.profile-header-bio= @user.roles.first.name.camelize
/   %nav.profile-header-nav
/     %ul.nav.nav-tabs
/       - if @user.student?
/         %li
/           = link_to user_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-comments-o{ style: "color: #50b36e; font-weight: bold;"}
/             Streamline
/         %li
/           = link_to medium_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-camera-retro{ style: "font-weight: bold; color: #3c9bcf;" }
/             Gallery
/         - if !current_user.business?
/           %li.active
/             = link_to user_ex_files_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/               %i.fa.fa-files-o{ style: "font-weight: bold; color: #000;" }
/               Exchange Notes
/       - elsif @user.business?
/         / -if @user.university?
/         /   %li
/         /     = link_to medium_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/         /       %i.fa.fa-camera-retro{ style: "color: #3097d1; font-weight: bold;" }
/         /       University Updates
/         /   %li
/         /     = link_to user_ex_files_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/         /       %i.fa.fa-folder-o{ style: "color: #3097d1; font-weight: bold;" }
/         /       University Folder
/         / - elsif @user.business?
/         %li
/           = link_to application_forms_path, style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-bookmark{ style: "color: #3c9bcf; font-weight: bold;" }
/             CV Library
/         %li
/           = link_to medium_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-newspaper-o{ style: "color: #d9c918; font-weight: bold;" }
/             Gallery
/         / %li
/         /   = link_to folders_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/         /     %i.fa.fa-files-o{ style: "color: #3097d1; font-weight: bold;" }
/         /     Company Reports
/         %li
/           = link_to user_job_applications_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-files-o{ style: "color: #bd502b; font-weight: bold;" }
/             Jobs Archive
/         %li
/           = link_to user_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;" do
/             %i.fa.fa-comments-o{ style: "color: #50b36e; font-weight: bold;"}
/             My Seeds
/       - if @user.student?
/         %li
/           = link_to user_benchmark_reports_path(@user.username), style: "font-size: 19px; font-weight: bold; color: #fff;", "data-no-turbolink" => true do
/             %i.fa.fa-area-chart{ style: "font-weight: bold; color: #bd502b;"}
/             Benchmark

app/views/ex_files/_list.html.haml
%h5
	%small
		%b= link_to "My documents", user_ex_files_path(current_user.username)
%ul.nav.nav-pills.nav-stacked
	%li
		= link_to new_user_ex_file_path(current_user.username) do
			%i.fa.fa-file
			%span Add File
	- if @exchange.any?
		- if @categories.any?
			- @categories.each do |category|
				%li
					= link_to user_ex_files_path(current_user.username, cat: category.slug) do
						%i.fa.fa-file-o
						%span= category.title
	%li
		= link_to "#" do
			%i.fa.fa-files-o
			%span Exchange Notes
	

app/views/ex_files/edit.html.haml
.container.better
	.row
		%h1 Editing File

		= render 'form'

		- if current_user == @user
			= link_to 'Show', user_ex_file_path(@user.username, @ex_file.guid)
			\|
		= link_to 'Back', user_ex_files_path(@user.username)

app/views/ex_files/index.html.haml
%div{ style: "padding-top: 35px;" }
-# .better{ style: "background-color: #30526E;" }
= render "header"
.container.m-y-md
  .row

    %h1 Listing Files

    %table.table
      %thead
        %tr
          / %th User
          %th Name
          / %th Description
          %th Category
          / %th Guid
          %th
          %th
          %th

      %tbody
        - @ex_files.each do |ex_file|
          %tr
            / %td= ex_file.user
            %td= ex_file.name
            / %td= ex_file.description
            %td= ex_file.category.title
            / %td= ex_file.guid
            %td= link_to 'Show', user_ex_file_path(@user.username, ex_file.guid)
            - if current_user == @user
              %td= link_to 'Edit', edit_user_ex_file_path(@user.username, ex_file.guid)
              %td= link_to 'Remove', user_ex_file_path(@user.username, ex_file.guid), :method => :delete, :data => { :confirm => 'Are you sure?' }
        %tr
          %td{"colspan" => 5}= link_to 'New Ex file', new_user_ex_file_path(current_user.username)

app/views/ex_files/new.html.haml
.container.better
	.row
		%h1 New File

		= render 'form'

		= link_to 'Back', user_ex_files_path(@user.username)

app/views/ex_files/show.html.haml
.container
  .row
    %p#notice= notice

    %p
      %b Name:
      = @ex_file.name
    %p
      %b Description:
      = @ex_file.description
    %p
      %b Category:
      = @ex_file.category.title

    - if @user == current_user
      = link_to 'Edit', edit_user_ex_file_path(@user.username, @ex_file.guid)
      \|
    = link_to 'Back', user_ex_files_path(@user.username)