config/routes.rb
Rails.application.routes.draw do
  resources :vita
  resources :yolos do
    resources :comments, module: :yolos
    member do
      put "like", to: "yolos#upvote"
      put "dislike", to: "yolos#downvote"
    end
  end

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  mount Soulmate::Server, :at => "/autocomplete"

  devise_for :users, controllers: {registrations: 'user_registrations'}

  get 'conversations/show'

  get 'conversations/create'

  resources :application_forms
  resources :media
  resources :groups do
    resources :posts, module: :groups
    member do
      get :join
      get :unfollow
    end
  end

  post '/buy/:slug', to: 'transactions#create', as: :buy

  resources :online_learnings
  resources :categories
  resources :videos
  resources :lectures
  resources :syllabuses
  resources :courses
  resources :polls
  resources :poll_votes, only: [:create]
  resources :community_posts

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :events do
    resources :posts, module: :events
  end

  get 'notifications/' => "notifications#index"

  resources :classifieds do
    resources :transactions, only: [:purchase, :create, :pickup], module: :classifieds
  end

  post "/hook" => "classifieds#hook"
  
  get "/classifieds/:id/purchase", to: "classifieds#purchase", as: :purchase_classified

  resources :posts, only: [:create, :edit, :update, :destroy] do
    resources :comments, module: :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :activities, only: [:index] do
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end

  resources :job_applications do
    resources :transactions, only: [:purchase, :create, :pickup], module: :job_applications
  end
  
  root 'pages#home'

  post "/activity_create" => "posts#create_from_activity"

  get "/about" => "pages#about"
  get "/community" => "pages#community"
  get "/contact" => "pages#contact"
  get "/copyright" => "pages#copyright"
  get "/privacy" => "pages#privacy"
  get "/terms" => "pages#terms"
  get "/toc" => "pages#toc"
  get "/cookies" => "pages#cpolicy"

  get "/find_university" => "pages#find_university"
  get "/find_tutor" => "pages#find_tutor"

  get '/users/:id/job_applications', to: 'job_applications#job_applications', as: 'user_job_applications'

  
  resources :users, only: [:show, :index]

  resources :detailbooks do
    resources :educations
    resources :job_experiences
  end
  resources :users do
    resources :posts, module: :users
    resources :educations
    resources :job_experiences
    resources :benchmark_reports, only: [:index, :show, :create, :new]
    resources :ex_files
    resources :skills
    resources :todo_tasks 
    resources :vita, only: [:index]
    resources :interest_activities
  end
  resources :skills
  resources :todo_tasks

  
  resources :friendships, only: [:create, :destroy, :accept] do 
    resources :comments, module: :friendships
    member do 
      put :accept
      put "like", to: "friendships#upvote"
      put "dislike", to: "friendships#downvote"
    end
  end

  resources :follows, only: [:follow, :unfollow] do
    member do
      get "follow"
      get "unfollow"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
.media
  .media-left
    = link_to user_path(conversation.originator.username) do
      = image_tag conversation.originator.avatar.url(:thumb), width: 64, height: 64, class: "img-circle"
      / %img.media-object{:src => "http://placehold.it/64x64", :alt => "..."}/
    
  .media-body
    %h4.media-heading
      = link_to user_path(conversation.originator.username) do
        = conversation.originator.full_name
      %br/
      %small
        %b Subject:
        = conversation.subject
      %br/
      %small
        %b Date:
        = conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p")

    = truncate conversation.messages.last.body, length: 145
    = link_to "View", conversation_path(conversation)

app/views/conversations/_form.html.haml
= form_for :conversation, url: :conversations, html: { class: "" } do |f|
  .form-group
    = f.label :recipients
    = f.select(:recipients, User.all.collect {|p| [ p.full_name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })
  .form-group
    = f.label :subject
    = f.text_field :subject, placeholder: "Subject", class: "form-control"
  .form-group
    = f.label :message
    = f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4
    
  = f.submit "Send Message", class: "btn btn-success"

app/views/conversations/_messages.html.haml
- @receipts.each do |receipt|
  - message = receipt.message
  .media
    .media-left
      / user avators can go here
      = link_to user_path(message.sender.username) do
        = image_tag message.sender.avatar.url(:thumb), width: 64, height: 64, class: "img-circle"

    .media-body
      %h4.media-heading
        = link_to user_path(message.sender.username) do
          = message.sender.full_name
        %br/
        %small
          %b Subject:
          = message.subject
        %br/
        %small
          %b Date: 
          = message.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
      = message.body

app/views/conversations/new.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: true }

app/views/conversations/show.html.haml
/ .better
/ .container.p-t-md
/   .row
/     .spacer
/     .col-md-12
/       = link_to "Compose", new_conversation_path, class: "btn btn-success"
/       .spacer

/     .col-md-4
/       .panel.panel-default
/         .panel-body
/           = render 'mailbox/folders'

/     .col-md-8
/       .panel.panel-default
/         .panel-body
/           = render partial: 'messages'
/         .panel-footer
/           / Reply Form
/           = form_for :message, url: reply_conversation_path(conversation) do |f|
/             .form-group
/               = f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control"
/             = f.submit "Reply", class: 'btn btn-danger pull-right'

/           .clearfix

.better
.container.p-t-md
  .row
    .spacer
    .col-md-6
      = link_to "Compose", new_conversation_path, class: "btn btn-success"
    .col-md-6.text-right
      - if conversation.is_trashed?(current_user)
        = link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post
      - else
        = link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post, data: {confirm: 'Are you sure?'}
      
  .row
    .spacer
    .col-md-4
      .panel.panel-default
        .panel-body
          = render 'mailbox/folders'

    .col-md-8
      .panel.panel-default
        .panel-body
          = render partial: 'messages'
        .panel-footer
          / Reply Form
          = form_for :message, url: reply_conversation_path(conversation) do |f|
            .form-group
              = f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control"
            = f.submit "Reply", class: 'btn btn-danger pull-right'
          .clearfix