config/routes.rb
Rails.application.routes.draw do
  resources :vita
  resources :yolos do
    resources :comments, module: :yolos
    member do
      put "like", to: "yolos#upvote"
      put "dislike", to: "yolos#downvote"
    end
  end

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  mount Soulmate::Server, :at => "/autocomplete"

  devise_for :users, controllers: {registrations: 'user_registrations'}

  get 'conversations/show'

  get 'conversations/create'

  resources :application_forms
  resources :media
  resources :groups do
    resources :posts, module: :groups
    member do
      get :join
      get :unfollow
    end
  end

  post '/buy/:slug', to: 'transactions#create', as: :buy

  resources :online_learnings
  resources :categories
  resources :videos
  resources :lectures
  resources :syllabuses
  resources :courses
  resources :polls
  resources :poll_votes, only: [:create]
  resources :community_posts

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :events do
    resources :posts, module: :events
  end

  get 'notifications/' => "notifications#index"

  resources :classifieds do
    resources :transactions, only: [:purchase, :create, :pickup], module: :classifieds
  end

  post "/hook" => "classifieds#hook"
  
  get "/classifieds/:id/purchase", to: "classifieds#purchase", as: :purchase_classified

  resources :posts, only: [:create, :edit, :update, :destroy] do
    resources :comments, module: :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :activities, only: [:index] do
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end

  resources :job_applications do
    resources :transactions, only: [:purchase, :create, :pickup], module: :job_applications
  end
  
  root 'pages#home'

  post "/activity_create" => "posts#create_from_activity"

  get "/about" => "pages#about"
  get "/community" => "pages#community"
  get "/contact" => "pages#contact"
  get "/copyright" => "pages#copyright"
  get "/privacy" => "pages#privacy"
  get "/terms" => "pages#terms"
  get "/toc" => "pages#toc"
  get "/cookies" => "pages#cpolicy"

  get "/find_university" => "pages#find_university"
  get "/find_tutor" => "pages#find_tutor"

  get '/users/:id/job_applications', to: 'job_applications#job_applications', as: 'user_job_applications'

  
  resources :users, only: [:show, :index]

  resources :detailbooks do
    resources :educations
    resources :job_experiences
  end
  resources :users do
    resources :posts, module: :users
    resources :educations
    resources :job_experiences
    resources :benchmark_reports, only: [:index, :show, :create, :new]
    resources :ex_files
    resources :skills
    resources :todo_tasks 
    resources :vita, only: [:index]
    resources :interest_activities
  end
  resources :skills
  resources :todo_tasks

  
  resources :friendships, only: [:create, :destroy, :accept] do 
    resources :comments, module: :friendships
    member do 
      put :accept
      put "like", to: "friendships#upvote"
      put "dislike", to: "friendships#downvote"
    end
  end

  resources :follows, only: [:follow, :unfollow] do
    member do
      get "follow"
      get "unfollow"
    end
  end

  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :vitum
  belongs_to :user

  has_attached_file :media
	# validates_attachment_presence :media_attachment
	validates_attachment_content_type :media,
		:content_type => ['video/mp4'],
		:message => "Sorry, right now we only support MP4 video",
		:if => :is_type_of_video?
	validates_attachment_content_type :media,
		:content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
		:message => "Different error message",
		:if => :is_type_of_image?

	protected

	def is_type_of_video?
		media.content_type =~ %r(video)
	end

	def is_type_of_image?
		media.content_type =~ %r(image)
	end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @educations = Education.all
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:guid, :school_institution, :date_start, :date_finish, :city, :country, :degree, :field_study, :grade, :activities_societies, :description, :done, :user_id, :media)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_form.html.haml
= simple_form_for(@education) do |f|
  = f.error_notification

  .form-inputs
    = f.input :guid
    = f.input :school_institution
    = f.input :date_start
    = f.input :date_finish
    = f.input :city
    = f.input :country
    = f.input :degree, label: "Degree Type", html_input: { class: "form-control"}, :collection => [["High School", 'High School'], ["Associate's Degree", "Associate's Degree"], ["Bachelor's Degree", "Bachelor's Degree"], ["Master's Degree", "Master's Degree"], ["Master of Business Administration (MBA)", "Master of Business Administration (MBA)"], ["Juris Doctor (JD)", "Juris Doctor (JD)"], ["Doctor of Medicine (MD)", "Doctor of Medicine (MD)"], ["Doctor of Philosophy (PhD)", "Doctor of Philosophy (PhD)"], ["Engineer's Degree", "Engineer's Degree"], ["Other", "Other"]], :label_method => :last, :value_method => :first, :as => :select
    = f.input :field_study
    = f.input :grade
    = f.input :activities_societies
    = f.input :description
    = f.input :done
    = f.association :detailbook

  .form-actions
    = f.button :submit

app/views/educations/edit.html.haml
%h1 Editing education

= render 'form'

= link_to 'Show', @education
\|
= link_to 'Back', educations_path

app/views/educations/index.html.haml
%h1 Listing educations

%table
  %thead
    %tr
      %th Guid
      %th School institution
      %th Date start
      %th Date finish
      %th City
      %th Country
      %th Degree
      %th Field study
      %th Grade
      %th Activities societies
      %th Description
      %th Done
      %th Detailbook
      %th
      %th
      %th

  %tbody
    - @educations.each do |education|
      %tr
        %td= education.guid
        %td= education.school_institution
        %td= education.date_start
        %td= education.date_finish
        %td= education.city
        %td= education.country
        %td= education.degree
        %td= education.field_study
        %td= education.grade
        %td= education.activities_societies
        %td= education.description
        %td= education.done
        %td= education.detailbook
        %td= link_to 'Show', education
        %td= link_to 'Edit', edit_education_path(education)
        %td= link_to 'Destroy', education, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Education', new_education_path

app/views/educations/new.html.haml
.container.better
	.row
		%h1 New education

		= render 'form'

		= link_to 'Back', detailbook_path(@detailbook)

app/views/educations/show.html.haml
.container.better
	.row
		%p#notice= notice

		%p
			%b School/Institution:
			= @education.school_institution
		%p
			%b Date Started:
			= @education.date_start.to_s(:long)
		%p
			%b Date Finished:
			= @education.date_finish.to_s(:long)
		%p
			%b City:
			= @education.city
		%p
			%b Country:
			= @education.country
		%p
			%b Degree:
			= @education.degree
		%p
			%b Field study:
			= @education.field_study
		%p
			%b Grade:
			= @education.grade
		%p
			%b Activities societies:
			= @education.activities_societies
		%p
			%b Description:
			= @education.description

		= link_to 'Edit', edit_detailbook_education_path(@education.detailbook, @education)
		\|
		= link_to 'Back', detailbook_path(@detailbook)